services:
    Aurelienazerty.DisplayLastPost.listener:
        class: Aurelienazerty\styleTA\event\listener
        arguments:
            - @dbal.conn
            - @config
            - @user
        tags:
            - { name: event.listener }
