services:
    Aurelienazerty.styleTA.listener:
        class: Aurelienazerty\styleTA\event\listener
        arguments:
            - @dbal.conn
            - @template
            - @user
        tags:
            - { name: event.listener }
